"""
Compute term scores by summing ranked gene values from a compact knowledge graph.

The script reads a pre-ranked gene list (``temp.rnk``-style, two columns of gene
symbol and numeric score) and a compact knowledge graph JSON generated by
``KG_preprocessing.py``. Each term's score is calculated as the sum of scores of
its directly connected genes. Results are written to ``GSEA_naive_output.txt``
containing the term label, source dataset (derived from edge relations), score,
and rank.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

GeneScores = Dict[str, float]


def load_gene_scores(path: Path) -> GeneScores:
    """Load gene scores from a whitespace-delimited ``.rnk`` file."""

    scores: GeneScores = {}
    with path.open(encoding="utf-8") as handle:
        for line_no, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            parts = stripped.split()
            if len(parts) < 2:
                raise ValueError(f"Invalid line #{line_no} in {path}: expected gene and score")
            gene, score_text = parts[0], parts[1]
            scores[gene] = float(score_text)
    return scores


def load_kg(path: Path) -> Dict[str, object]:
    """Load the compact knowledge graph JSON."""

    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def build_term_gene_maps(triples: Sequence[Dict[str, str]]) -> Tuple[Dict[str, List[str]], Dict[str, List[str]]]:
    """Create mappings from term labels to genes and datasets (relations)."""

    term_to_genes: Dict[str, List[str]] = defaultdict(list)
    term_to_datasets: Dict[str, List[str]] = defaultdict(list)
    for triple in triples:
        term_label = triple["source_label"]
        gene_label = triple["target_label"]
        relation = triple["relation"]
        term_to_genes[term_label].append(gene_label)
        term_to_datasets[term_label].append(relation)
    return term_to_genes, term_to_datasets


def compute_term_scores(
    term_to_genes: Dict[str, List[str]], gene_scores: GeneScores
) -> Dict[str, float]:
    """Sum scores for genes directly connected to each term."""

    scores: Dict[str, float] = {}
    for term, genes in term_to_genes.items():
        scores[term] = sum(gene_scores.get(gene, 0.0) for gene in genes)
    return scores


def format_dataset_label(relations: Iterable[str]) -> str:
    """Create a stable dataset label string from relations."""

    unique = sorted(set(relations))
    return ",".join(unique)


def write_output(
    output_path: Path,
    term_scores: Dict[str, float],
    term_to_datasets: Dict[str, List[str]],
) -> None:
    """Write sorted term scores with dataset and rank to a file."""

    sorted_terms = sorted(
        term_scores.items(), key=lambda item: (-item[1], item[0])
    )

    lines = ["term_label\tdataset\tscore\trank"]
    for idx, (term, score) in enumerate(sorted_terms, start=1):
        dataset_label = format_dataset_label(term_to_datasets.get(term, []))
        lines.append(f"{term}\t{dataset_label}\t{score}\t{idx}")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute naive GSEA-style term scores from a compact KG and ranked genes."
    )
    parser.add_argument(
        "--rnk", type=Path, default=Path("temp.rnk"), help="Path to the ranked gene list file."
    )
    parser.add_argument(
        "--kg", type=Path, default=Path("data/compact_kg.json"), help="Path to the compact KG JSON file."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("GSEA_naive_output.txt"),
        help="Destination file for term scores and ranks.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    gene_scores = load_gene_scores(args.rnk)
    kg = load_kg(args.kg)

    term_to_genes, term_to_datasets = build_term_gene_maps(kg.get("triples", []))
    term_scores = compute_term_scores(term_to_genes, gene_scores)

    output_path = args.output if args.output.is_absolute() else args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_output(output_path, term_scores, term_to_datasets)

    print(f"Wrote term scores for {len(term_scores)} terms to {output_path}")


if __name__ == "__main__":
    main()